### PR TITLE
add regenerator-runtime to fix bugs about babel >= 7.5.0

### PR DESCRIPTION
**Pull request by jlbousing**

### CODE REVIEW

**Comment by jlbousing** [comment]
I had a error about regeneratorRuntime is not defined in dist/index.js of this module. I want fixed add core-js: stable version (I think this will help) and regenerator-runtime: stable-version. If you think this update will fix the bug, please try it and merge it. If you want conctact me, you can text me to jbousing@gmail.com or @KingBousing in Twitter. Greeting from Venezuela

**Comment by adi518** [comment]
Hi, would be best if you can start a new issue and link it to this PR. Thanks.

**Comment by adi518** [comment]
> Is this being considered? I'm currently getting this error as well.

I'm on it.

**Comment by adi518** [comment]
I'm not getting this error. You'll have to post a repro.

**Comment by adi518** [comment]
If this issue persists, please open an issue and we'll continue from there.

**Pull request closed without merging**
